apiVersion: v1
kind: Service
metadata:
  name: todolistsrv1
  labels:
    app: todosrv
spec:
  ports:
    - port: 8086
      name: web
      targetPort: 8086
    - port: 50051
      name: grpcc
      targetPort: 50051
  clusterIP: None
  selector:
    app: todosrv